In [1]:
import numpy as np
%matplotlib inline

In [2]:
matrixA = np.array([[2,-4,7], [3,-3,0], [1,7,5]])

matrixB = np.array([[2,4], [3,-3], [1,7]])

matrixC = np.array([[-1,1], [1,-1]])

matrixD = np.array([[2,0], [-3,6]])

print(matrixA)
print()
print(matrixB)
print()
print(matrixC)
print()
print(matrixD)

[[ 2 -4  7]
 [ 3 -3  0]
 [ 1  7  5]]

[[ 2  4]
 [ 3 -3]
 [ 1  7]]

[[-1  1]
 [ 1 -1]]

[[ 2  0]
 [-3  6]]


In [3]:
matrixAnew = matrixA * 2.5

print(matrixAnew)

[[  5.  -10.   17.5]
 [  7.5  -7.5   0. ]
 [  2.5  17.5  12.5]]


In [4]:
'''
matrixA * matrixC
print(matrixA)
'''

#this code won't run because the two matrices have different column dimensions

'\nmatrixA * matrixC\nprint(matrixA)\n'

In [7]:
CD = np.matmul(matrixC, matrixD)
print(CD)
print()

DC = np.matmul(matrixD, matrixC)
print(DC)

[[-5  6]
 [ 5 -6]]

[[-2  2]
 [ 9 -9]]


In [8]:
print(matrixB)
print()

matrixBT = matrixB.T
print(matrixBT)

[[ 2  4]
 [ 3 -3]
 [ 1  7]]

[[ 2  3  1]
 [ 4 -3  7]]


In [9]:
print(matrixC)
print(matrixD)
print()

addmCD = matrixC + matrixD
print(addmCD)

[[-1  1]
 [ 1 -1]]
[[ 2  0]
 [-3  6]]

[[ 1  1]
 [-2  5]]


In [10]:
print(matrixC)
print()

detC = np.linalg.det(matrixC)
print(detC)

[[-1  1]
 [ 1 -1]]

0.0


In [11]:
print(matrixA)
print()

detA = np.linalg.det(matrixA)
print(detA)

[[ 2 -4  7]
 [ 3 -3  0]
 [ 1  7  5]]

197.9999999999998
