In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook

In [3]:
matrix = np.array([[11,-1,0], [-1,12,-1], [0,-1,11]])
print(matrix)

[[11 -1  0]
 [-1 12 -1]
 [ 0 -1 11]]


In [5]:
w,v = np.linalg.eig(matrix)
print('E-value:', w)
print('E-vector:', v)

E-value: [13. 11. 10.]
E-vector: [[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  1.22910000e-15  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
